name: XWiki Commons CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: xwiki/build
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
      - name: Build with Maven
        run: |
          /home/hudsonagent/maven/bin/mvn --version

