name: XWiki Commons CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: xwiki/build
    steps:
      - name: Checkout sources
        uses: actions/checkout@master
      - name: Scope for Maven Action
        uses: undefinedlabs/scope-for-maven-action@v1
        with:
          dsn: ${{secrets.SCOPE_DSN}}
          command: /home/hudsonagent/maven/bin/mvn --no-transfer-progress install -Dmaven.test.failure.ignore -Dxwiki.license.skip=true -Plegacy,integration-tests,docker,snapshot 
#      - name: Build with Maven
#        run: |
#          export MAVEN_OPTS="-Xmx2048m -Xms512m"
#          /home/hudsonagent/maven/bin/mvn --no-transfer-progress install -Dmaven.test.failure.ignore -Plegacy,integration-tests,docker,snapshot
#      - name: Publish Test Results
#        uses: check-run-reporter/action@master
#        env:
#          CHECK_RUN_REPORTER_LABEL: 'Unit Tests for Commons'
#          CHECK_RUN_REPORTER_REPORT: '**/target/surefire-reports/**/*.xml'
#          CHECK_RUN_REPORTER_TOKEN: ${{ secrets.CHECK_RUN_REPORTER_TOKEN }}
